before_install:
    -   echo "deb http://apt.opscode.com/ precise-0.10 main" | sudo tee /etc/apt/sources.list.d/opscode.list
    -   sudo mkdir -p /etc/apt/trusted.gpg.d
    -   gpg --keyserver keys.gnupg.net --recv-keys 83EF826A
    -   gpg --export packages@opscode.com | sudo tee /etc/apt/trusted.gpg.d/opscode-keyring.gpg > /dev/null
    -   sudo apt-get update -qq
    -   sudo apt-get install -qq chef

script:
    -   sudo ./deploy

after_failure:
    -   ls -l /home/czchen
